### ISSUE TITLE
example does not work: __init__() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by freisei** [ehdgua01/blocksync#1]
Hi!

I tried to swtich from blocksync-script to your module, but i'm unable to start the modified example:

> 
> 
> import blocksync
> 
> source_file = blocksync.File(
>     "/dev/vgmain1/bsyncsourcetest",
>     remote=True,
>     hostname="ip.jbplan.de",
>     username="root",
>     password="example_password",
>     compress=True,
>     port=2201,
>     key_filename="/root/.ssh/id_ecdsa",
>     cipher="aes128-ctr",
> )
> destination_file = blocksync.File("/dev/vg2/pb_bsyncsourcetest", remote=False)
> syncer = blocksync.Syncer(source_file, destination_file)
> 

`root@xp8rz2main2:/opt/btt2# ./btt2.py
Traceback (most recent call last):
  File "./btt2.py", line 86, in <module>
    syncer = blocksync.Syncer(source_file, destination_file)
TypeError: __init__() takes 1 positional argument but 3 were given
`
Is this an error in Module or am i doing something wrong?

**Comment by ehdgua01** [comment]
Hi, @freisei 

I'm sorry, I wrote a wrong example.
Can you try it like this?
```python
import blocksync

...
syncer = blocksync.Syncer()
syncer.set_source(source_file)
syncer.set_destination(destination_file)
```

**Comment by freisei** [comment]
Thanks for your answer.

```
import blocksync

source_file = blocksync.File(
    "/dev/vgmain1/bsyncsourcetest",
    remote=True,
    hostname="ip.jbplan.de",
    username="root",
    password="example_password",
    compress=True,
    port=2201,
    key_filename="/root/.ssh/id_ecdsa",
    cipher="aes128-ctr",
)
destination_file = blocksync.File("/dev/vg2/pb_bsyncsourcetest", remote=False)
syncer = blocksync.Syncer()
syncer.set_source(source_file)
syncer.set_destination(destination_file)

syncer.start_sync()

```

I tried it, now i run into the next error:
```

root@xp8rz2main2:/opt/btt2# ./btt2.py
Not exists destination file
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/blocksync/syncer.py", line 284, in _sync
    self.source.do_close()
  File "/usr/local/lib/python3.8/dist-packages/blocksync/file.py", line 99, in do_close
    self.close_sftp()
  File "/usr/local/lib/python3.8/dist-packages/blocksync/file.py", line 75, in close_sftp
    self._local.sftp.close()
AttributeError: '_thread._local' object has no attribute 'sftp'
```
dest-file exists:
```
root@xp8rz2main2:/opt/btt2# ls -la /dev/vg2/pb_bsyncsourcetest
lrwxrwxrwx 1 root root 8 Mar 19 08:15 /dev/vg2/pb_bsyncsourcetest -> ../dm-24

root@xp8rz2main2:/opt/btt2# python3 --version
Python 3.8.5
```

**Comment by ehdgua01** [comment]
Can you check your source file if exists in your remote?

**Comment by freisei** [comment]
Thanks for your fast reply.

Source file exists. the error was because of lacking public-ssh-key on source and no accompished dialog of host-key-check. 
This was because of reinstalling the target-server to get the same python3-version.

Some better error-descriptions would be fine for this case.

But now, the next problem is here:

The code runs fine, no error, no output, only 2 secs runtime: But: even no sync. The files are different and after sync the destination is unchanged.
Even no output.
On source and target there is no relevant hdd-activity. So i think the files are even not compared.

```
root@xp8rz2main2:/opt/btt2# ssh -p 2201 ip.jbplan.de md5sum /dev/vgmain1/bsyncsourcetest
6c29436efb860e49652725d9ec3b4355  /dev/vgmain1/bsyncsourcetest
root@xp8rz2main2:/opt/btt2# ssh -p 2201 ip.jbplan.de blockdev --getsz /dev/vgmain1/bsyncsourcetest
83886080

```

```
root@xp8rz2main2:/opt/btt2# md5sum /dev/vg2/pb_bsyncsourcetest

e007e927be5b0ed765c2e35a572526c8  /dev/vg2/pb_bsyncsourcetest
root@xp8rz2main2:/opt/btt2#
root@xp8rz2main2:/opt/btt2# ./btt2.py
root@xp8rz2main2:/opt/btt2# md5sum /dev/vg2/pb_bsyncsourcetest
e007e927be5b0ed765c2e35a572526c8  /dev/vg2/pb_bsyncsourcetest
root@xp8rz2main2:/opt/btt2# blockdev --getsz /dev/vg2/pb_bsyncsourcetest
83886080
```



btw there is no warning when source and target sizes differ - i think that would be useful.

**Comment by ehdgua01** [comment]
Hi, @freisei 

Try using v1.2.0.
I tested all examples and checked that the destination file was synchronized.

**Comment by freisei** [comment]
Hi @ehdgua01 
with 1.2.0 it works to sync a regular file vom remote-source to local target:

```
import blocksync

source_file = blocksync.File(
    "/tmp/pb_random_source",
    remote=True,
    hostname="ip.jbplan.de",
    port=2201,
    username="root",
    #password="example_password",
    key_filename="/root/.ssh/id_ecdsa",
    compress=True,
    # cipher="aes128-ctr",
)
destination_file = blocksync.File("/tmp/pb_random_dest")
syncer = blocksync.Syncer(source_file, destination_file)
syncer.start_sync()

```

but it does not work to sync from remote lvm-source to local lvm target.

```
import blocksync

source_file = blocksync.File(
    "/dev/vgmain1/pb_random_source",
    remote=True,
    hostname="ip.jbplan.de",
    port=2201,
    username="root",
    #password="example_password",
    key_filename="/root/.ssh/id_ecdsa",
    compress=True,
    # cipher="aes128-ctr",
)
destination_file = blocksync.File("/dev/vg2/pb_random_dest")
syncer = blocksync.Syncer(source_file, destination_file)
syncer.start_sync()

```


```
root@xp8rz2main2:/opt/btt2# ssh -p 2201 ip.jbplan.de md5sum /dev/vgmain1/pb_random_source
c794e6d5c1ca39e76bcf8143baa77e8f  /dev/vgmain1/pb_random_source

root@xp8rz2main2:/opt/btt2# date; python3 ./blocksync_test_lvm.py; date
Sat Mar 27 09:27:13 CET 2021
Sat Mar 27 09:27:16 CET 2021

9a29b9069236bfb616ca85c2223d53b3  /dev/vg2/pb_random_dest
```

as you see the command script is done very much to fast (3 seconds, i would expect around about over 100 seconds for 100mb to sync over a 10Mbit/s wire.

btw i am mostly on PC today and have time to immidiatly test your changes.

**Comment by ehdgua01** [comment]
Synchronization ends so quickly because it works on a thread by default.
You can use the option `sync.start_sync(wait=True)` to wait until the synchronization is over.
I think Syncer synchronizes LVM volumes is no different from regular files.

**Comment by freisei** [comment]
`Synchronization ends so quickly because it works on a thread by default.`
i used the same settings, just changed the filenames. With files instead of lvm-source/dests sync-script is blocking for some minutes.

` I think Syncer synchronizes LVM volumes is no different from regular files.`
i would assume the same, but in fact it isnt.

destination is untouched even after hours, i looks like lvm-source isnt even read.
```
root@xp8rz2main2:/opt/btt2# md5sum /dev/vg2/pb_random_dest
9a29b9069236bfb616ca85c2223d53b3  /dev/vg2/pb_random_dest
```

**Comment by freisei** [comment]
i would try to debug by myself, but i´m not good at python3, and there are so much files and programatic-schemes which i don´t know.

**Comment by freisei** [comment]
`syncer.start_sync(wait=True)` didn´t change anything. just 2 seconds of runtime, dest is unchanged.

**Comment by ehdgua01** [comment]
I added an error log with a stack trace in this commit(https://github.com/ehdgua01/blocksync/commit/bc655570fe79c46527d7747e3f0fec7925d05740), so you can debug easier..
You should upgrade blocksync using this commit id (e.g. `pip install blocksync @ "git+https://github.com/ehdgua01/blocksync@bc655570fe79c46527d7747e3f0fec7925d05740"`
